version: '3.7'
services:
  web:
    build: .
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV}
      TZ: ${TZ}
    volumes:
      - ./:/go/src/app:delegated
    ports:
      - "8080:8080"
    working_dir: /go/src/app
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:delegated

volumes:
  db_data:
