version: '3.7'
services:
  web:
    build: .
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV}
      TZ: ${TZ}
    volumes:
      - ./:/go/src/github.com/aberyotaro/gql-sample-api:delegated
    ports:
      - "80:80"
      - "443:443"
    working_dir: /go/src/github.com/aberyotaro/gql_sample_api
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
